# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YYShareTool' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for YYShareTool


pod 'Masonry'
pod 'UMCCommon'
pod 'UMCSecurityPlugins'
pod 'UMCShare/Social/ReducedWeChat'


end
